version: '3'

services:
  oohub:
    build: 
      context: .
      dockerfile: ./jupyterhub/Dockerfile
    expose: 
      - 8000
    ports:
      - "8000:8000"
    volumes:
      -  ./jupyterhub/:/src/jupyterhub/
    restart: always 
    stdin_open: true
    tty : true 
