version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: ./oohub-fe/Dockerfile
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - ./oohub-fe:/frontend
      - /frontend/node_modules
#     stdin_open: true
#     tty: true
    restart: always

  backend:
    build:
      context: .
      dockerfile: ./oohub-be/Dockerfile
    expose:
      - 8080
    ports:
      - "8080:8080"
    links:
      - mysql_db:mysql_db
    depends_on:
      - mysql_db
    volumes:
      - ./build/libs/:/backend/
      - ${HOME}/:/my-local/
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/oohub?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    restart: always
    stdin_open: true
    tty: true

  mysql_db:
    image: mysql:latest
    restart: always
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/:ro
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=oohub
      - MYSQL_ROOT=%
      - MYSQL_PASSWORD=1234

  nginx:
    image: nginx:latest
    ports:
      - "3001:3001"
      - "8081:8081"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    restart: "on-failure"

